/**
 * 编辑本文件后，请把 window.DARLINK_ONBOARDING 段落同步到 questionnaire-data.js 末尾。
 * questionnaire-data.js 是线上实际加载的文件（nginx 已配置）。
 */
window.DARLINK_ONBOARDING = {
  version: "20260704-step3-chat-10",

  summaryOk: {
    en: "No problem~",
    zhHans: "没问题～",
    zhHant: "沒問題～",
  },

  ui: {
    en: {
      step1: "Step 1/3 · Foundation questionnaire",
      panelFoundation: "Foundation questionnaire",
      formCaption: "Fill in your basics once — no chat needed.",
      next1: "Continue to persona distillation",
    },
    zhHans: {
      step1: "步骤 1/3 · 基础信息问卷",
      panelFoundation: "基础信息问卷",
      formCaption: "一次性填写基础信息，比逐题对话更快。",
      next1: "进入人物画像蒸馏",
    },
    zhHant: {
      step1: "步驟 1/3 · 基礎資訊問卷",
      panelFoundation: "基礎資訊問卷",
      formCaption: "一次性填寫基礎資訊，比逐題對話更快。",
      next1: "進入人物畫像蒸餾",
    },
  },

  questionText: {
    en: {
      nickname: "What nickname would you like people to call you?",
      school: "Which university are you from? Please use the official school name.",
      goal: "What kind of connection are you mainly looking for now: study partner, social companion, or romance?",
      grade: "Which year or study stage are you in?",
      majorDirection: "What is your major or academic direction?",
      selfWords: "Optional: use three words to describe yourself.",
      chatStyle: "Optional: what kind of chat style feels most like you?",
      tabooTopics: "Optional (multi-select): topics you'd rather new people avoid at first.",
      heightWeight: "Optional: share height/weight only if you want.",
      joke: "Send me a joke, meme style, or one sentence that represents your humor.",
      catchphrase: "What phrase do you often say when you are relaxed?",
      personality: "What's your MBTI type? (Optional — skip if you don't know.)",
      memory: "Tell me one experience that shaped how you make friends or trust people.",
      intent: "Which path should Xiaoda open first: Study Sync, Social Companion, or Deep Romance?",
    },
    zhHans: {
      nickname: "你希望别人怎么称呼你？可以是昵称。",
      school: "你来自哪所高校？请写学校官方名称。",
      goal: "你现在最想找哪类连接：学习伙伴、社交搭子，还是恋爱对象？",
      grade: "你现在是几年级或哪个学习阶段？",
      majorDirection: "你的专业或学科方向是什么？",
      selfWords: "选填：用三个词形容你自己。",
      chatStyle: "选填：什么样的聊天方式最像你？",
      tabooTopics: "选填：初次认识时你不希望对方触碰的话题。",
      heightWeight: "选填：身高体重只有你愿意才需要说。",
      joke: "发我一个能代表你幽默感的梗、玩笑或一句话。",
      catchphrase: "你放松的时候常说的一句话是什么？",
      personality: "你的 MBTI 是什么？（选填，不知道可跳过）",
      memory: "讲一个影响你交朋友或信任他人的经历。",
      intent: "你希望小搭先开启哪条路径：学习搭子、社交搭子，还是深度恋爱？",
    },
    zhHant: {
      nickname: "你希望別人怎麼稱呼你？可以是暱稱。",
      school: "你來自哪所高校？請寫學校官方名稱。",
      goal: "你現在最想找哪類連接：學習夥伴、社交搭子，還是戀愛對象？",
      grade: "你現在是幾年級或哪個學習階段？",
      majorDirection: "你的專業或學科方向是什麼？",
      selfWords: "選填：用三個詞形容你自己。",
      chatStyle: "選填：什麼樣的聊天方式最像你？",
      tabooTopics: "選填：初次認識時你不希望對方觸碰的話題。",
      heightWeight: "選填：身高體重只有你願意才需要說。",
      joke: "發我一個能代表你幽默感的梗、玩笑或一句話。",
      catchphrase: "你放鬆的時候常說的一句話是什麼？",
      personality: "你的 MBTI 是什麼？（選填，不知道可跳過）",
      memory: "講一個影響你交朋友或信任他人的經歷。",
      intent: "你希望小搭先開啟哪條路徑：學習搭子、社交搭子，還是深度戀愛？",
    },
  },

  step1Fields: [
    { id: "nickname", type: "text", required: true },
    { id: "school", type: "text", required: true },
    { id: "goal", type: "choice", required: true, optionsKey: "goal" },
    { id: "grade", type: "text", required: true },
    { id: "majorDirection", type: "text", required: true },
    { id: "selfWords", type: "text", optional: true },
    { id: "chatStyle", type: "choice", optional: true, optionsKey: "chatStyle" },
    { id: "tabooTopics", type: "multi", optional: true, optionsKey: "taboo" },
    { id: "heightWeight", type: "text", optional: true, romanceOnly: true },
  ],


  step3StudyQuestions: [
    { id: "study_core_01", required: true },
    { id: "study_core_07", required: true },
    { id: "study_core_04", required: true },
    { id: "study_core_02", required: true },
    { id: "study_core_09", required: true },
    { id: "study_core_08", required: true },
    { id: "study_core_12", required: true },
    { id: "study_core_11", required: true },
    { id: "study_core_10", required: true },
    { id: "study_core_15", required: true },
  ],

  studyQuestionText: {
    en: {
      study_core_01: "How do you prefer to study together: online or offline?",
      study_online_methods: "Which online channels work for you? (You can pick more than one)",
      study_offline_methods: "Which offline formats work for you? (You can pick more than one)",
      study_core_02: "When are you most efficient for deep study?",
      study_core_03: "What's your ideal continuous study block?",
      study_core_04: "How often do you want to sync with a study partner each week?",
      study_core_05: "When learning something new, which channel helps you most?",
      study_core_06: "What study environment helps you focus best?",
      study_core_07: "What kind of matching goal are you aiming for?",
      study_core_08: "What mainly fuels your learning drive?",
      study_core_09: "What role do you hope a study partner plays for you?",
      study_core_11: "If your partner gets stuck on something you're good at, you tend to…",
      study_core_10: "If a teammate free-rides on group work, you would…",
      study_core_12: "How would you describe your study self-control — heavy procrastinator or strong executor?",
      study_core_13: "When your study plan gets disrupted by sudden tasks, you usually…",
      study_core_15: "How should your partner's major relate to yours?",
    },
    zhHans: {
      study_core_01: "你想要以什么方式进行学习交流？",
      study_online_methods: "你想采取什么方式进行线上交流？",
      study_offline_methods: "你想采取什么方式进行线下交流？",
      study_core_02: "你的高效学习时段偏好是？",
      study_core_03: "你理想的单次连续学习时长是？",
      study_core_04: "你每周能接受的与学习伙伴同步互动（线上/线下同步交流）频率是？",
      study_core_05: "输入新知识时，你依赖的「第一感官通道」是？",
      study_core_06: "你习惯的学习环境氛围是？",
      study_core_07: "你进行匹配的目标属于哪一类？",
      study_core_08: "驱动你学习的核心燃料是什么？",
      study_core_09: "你希望学习伙伴在关系中扮演什么角色？",
      study_core_11: "学习伙伴在做一道你非常擅长的题时突然卡壳了，你倾向于？",
      study_core_10: "假如你的队友出现了「搭便车」的情况，你会怎么处理？",
      study_core_12: "你怎么评价自己的学习自控力？是容易拖延，还是执行力很强？",
      study_core_13: "当你学习计划被突发琐事（如会议、紧急任务）打乱时，你的情绪反应是？",
      study_core_15: "你希望伙伴的专业与你是什么关系？",
    },
    zhHant: {
      study_core_01: "你想要以什麼方式進行學習交流？",
      study_online_methods: "你想採取什麼方式進行線上交流？",
      study_offline_methods: "你想採取什麼方式進行線下交流？",
      study_core_02: "你的高效學習時段偏好是？",
      study_core_03: "你理想的單次連續學習時長是？",
      study_core_04: "你每週能接受的與學習夥伴同步互動（線上/線下同步交流）頻率是？",
      study_core_05: "輸入新知識時，你依賴的「第一感官通道」是？",
      study_core_06: "你習慣的學習環境氛圍是？",
      study_core_07: "你進行匹配的目標屬於哪一類？",
      study_core_08: "驅動你學習的核心燃料是？",
      study_core_09: "你希望學習夥伴在關係中扮演什麼角色？",
      study_core_11: "學習夥伴在做一道你非常擅長的題時突然卡殼了，你傾向於？",
      study_core_10: "假如你的隊友出現了「搭便車」的情況，你會怎麼處理？",
      study_core_12: "你怎麼評價自己的學習自控力？是容易拖延，還是執行力很強？",
      study_core_13: "當你學習計劃被突發瑣事（如會議、緊急任務）打亂時，你的情緒反應是？",
      study_core_15: "你希望夥伴的專業與你是什麼關係？",
    },
  },

  step3SocialQuestions: [
    { id: "friend_core_01", required: true },
    { id: "friend_core_02", required: true },
    { id: "friend_core_03", required: true },
    { id: "friend_core_06", required: true },
    { id: "friend_core_07", required: true },
    { id: "friend_core_08", required: true },
    { id: "friend_core_09", required: true },
    { id: "friend_core_10", required: true },
    { id: "friend_core_14", required: true },
    { id: "friend_core_15", required: true },
  ],

  socialQuestionText: {
    en: {
      friend_core_01: "What kind of buddy are you mainly looking for on Darlink?",
      friend_core_02: "What is your core motivation for social activities?",
      friend_core_03: "What social group size do you prefer?",
      friend_core_06: "What interaction frequency feels ideal with a buddy?",
      friend_core_07: "If a buddy asks \"want to grab food?\" one hour before mealtime, you usually…",
      friend_core_08: "In a shared activity (meal, short trip), you usually play which role?",
      friend_core_09: "When you want restaurant A but your buddy wants B, you tend to…",
      friend_core_10: "For a typical hangout (meal, tea, tickets), what per-person budget feels right to you?",
      friend_core_14: "What's the maximum spatial distance you can accept with a buddy?",
      friend_core_15: "How much do shared interests matter in matching?",
    },
    zhHans: {
      friend_core_01: "你最想通过本平台寻找的「搭子」类型是？",
      friend_core_02: "你参与社交活动的核心动力是什么？",
      friend_core_03: "你理想的社交规模通常是？",
      friend_core_06: "你与搭子理想的互动频率是？",
      friend_core_07: "如果搭子在饭点前一小时突然问「出来吃饭吗」，你的反应是？",
      friend_core_08: "在一次共同活动中（如聚餐、短途游），你习惯扮演的角色是？",
      friend_core_09: "当你想吃 A 店但搭子想吃 B 店时，你的本能反应是？",
      friend_core_10: "一次搭子活动（吃饭/下午茶/门票等），你觉得合适的人均消费大概是多少？",
      friend_core_14: "你能接受与搭子的最大空间距离是？",
      friend_core_15: "对于共同兴趣的匹配程度，你的要求是？",
    },
    zhHant: {
      friend_core_01: "你最想通過本平台尋找的「搭子」類型是？",
      friend_core_02: "你參與社交活動的核心動力是什麼？",
      friend_core_03: "你理想的社交規模通常是？",
      friend_core_06: "你與搭子理想的互動頻率是？",
      friend_core_07: "如果搭子在飯點前一小時突然問「出來吃飯嗎」，你的反應是？",
      friend_core_08: "在一次共同活動中（如聚餐、短途遊），你習慣扮演的角色是？",
      friend_core_09: "當你想吃 A 店但搭子想吃 B 店時，你的本能反應是？",
      friend_core_10: "一次搭子活動（吃飯/下午茶/門票等），你覺得合適的人均消費大概是多少？",
      friend_core_14: "你能接受與搭子的最大空間距離是？",
      friend_core_15: "對於共同興趣的匹配程度，你的要求是？",
    },
  },

  step3RomanceQuestions: [
    { id: "romance_core_01", required: true },
    { id: "romance_core_02", required: true },
    { id: "romance_core_03", required: true },
    { id: "romance_core_04", required: true },
    { id: "romance_core_05", required: true },
    { id: "romance_core_06", required: true },
    { id: "romance_core_07", required: true },
    { id: "romance_core_08", required: true },
    { id: "romance_core_10", required: true },
    { id: "romance_core_11", required: true },
  ],

  romanceQuestionText: {
    en: {
      romance_core_01: "What is your main intention in looking for a romance partner right now?",
      romance_core_02: "What relationship pacing feels most natural to you?",
      romance_core_03: "Which traits matter most to you in a partner?",
      romance_core_04: "What daily contact rhythm do you prefer with a partner?",
      romance_core_05: "How much personal space do you need in an intimate relationship?",
      romance_core_06: "When you and a partner have a heated argument, you tend to…",
      romance_core_07: "Regarding opposite-sex friendships, your stance is closer to…",
      romance_core_08: "How much difference in spending/money views can you accept?",
      romance_core_09: "In give-and-take, which pattern feels closest to you?",
      romance_core_10: "For a lasting healthy relationship, the indispensable foundation is…",
      romance_core_11: "What kind of match would you like the algorithm to find for you?",
    },
    zhHans: {
      romance_core_01: "你目前寻找恋爱对象的主要意图是？",
      romance_core_02: "你更适应哪种恋爱推进节奏？",
      romance_core_03: "在伴侣身上，你最看重哪些特质？",
      romance_core_04: "你理想中与伴侣的日常联络密度是？",
      romance_core_05: "在亲密关系中，你需要多少「个人空间」？",
      romance_core_06: "当你与伴侣发生激烈争执时，你的本能反应更接近于？",
      romance_core_07: "关于伴侣的异性交往边界，你更接近哪种态度？",
      romance_core_08: "消费与金钱观方面，你更愿意接受与伴侣之间存在多大差异？",
      romance_core_09: "在付出与回报的感知上，你内心更接近哪种模式？",
      romance_core_10: "你认为一段长久健康的恋爱关系，最不可或缺的基石是？",
      romance_core_11: "你更希望算法为你匹配怎样的潜在对象？",
    },
    zhHant: {
      romance_core_01: "你目前尋找戀愛對象的主要意圖是？",
      romance_core_02: "你更適應哪種戀愛推進節奏？",
      romance_core_03: "在伴侶身上，你最看重哪些特質？",
      romance_core_04: "你理想中與伴侶的日常聯絡密度是？",
      romance_core_05: "在親密關係中，你需要多少「個人空間」？",
      romance_core_06: "當你與伴侶發生激烈爭執時，你的本能反應更接近於？",
      romance_core_07: "關於伴侶的異性交往邊界，你更接近哪種態度？",
      romance_core_08: "消費與金錢觀方面，你更願意接受與伴侶之間存在多大差異？",
      romance_core_09: "在付出與回報的感知上，你內心更接近哪種模式？",
      romance_core_10: "你認為一段長久健康的戀愛關係，最不可或缺的基石是？",
      romance_core_11: "你更希望算法為你匹配怎樣的潛在對象？",
    },
  },

  step2Questions: [
    { id: "summaryConfirm", required: true, summaryGate: true },
    { id: "joke", optional: true },
    { id: "catchphrase", required: true },
    { id: "personality", optional: true },
    { id: "memory", required: true },
  ],

  options: {
    socialBuddyType: {
      en: ["Chat / emotional support", "Food buddy", "Travel buddy", "Interest buddy", "All-round buddy"],
      zhHans: ["纯聊天 / 情绪树洞（分享日常）", "饭搭子（探店、约食堂、吃吃喝喝）", "旅游搭子（短途/长假出游，需要同频的行程观）", "兴趣搭子（游戏开黑、运动、阅读、追星等特定爱好）", "万能搭子（以上皆可，更看重人本身）"],
      zhHant: ["純聊天 / 情緒樹洞（分享日常）", "飯搭子（探店、約食堂、吃吃喝喝）", "旅遊搭子（短途/長假出遊，需要同頻的行程觀）", "興趣搭子（遊戲開黑、運動、閱讀、追星等特定愛好）", "萬能搭子（以上皆可，更看重人本身）"],
    },
    socialMotivation: {
      en: ["Ease loneliness", "Fun and fresh experiences", "Resonance / being understood", "Practical mutual help"],
      zhHans: ["缓解孤独，需要有人陪着", "获得快乐与新鲜体验（吃到一起、玩到一起）", "寻找同频共鸣（有人能懂我的点）", "纯粹功利性互助（拼车、拼单、拼团）"],
      zhHant: ["緩解孤獨，需要有人陪著", "獲得快樂與新鮮體驗（吃到一起、玩到一起）", "尋找同頻共鳴（有人能懂我的點）", "純粹功利性互助（拼車、拼單、拼團）"],
    },
    socialGroupSize: {
      en: ["One-on-one", "Trio", "Larger group (4+)", "Depends on the activity"],
      zhHans: ["一对一深度交流（典型搭子模式）", "三人小团体（平衡热闹与深入）", "多人热闹局（4人以上，适合桌游/聚餐）", "无所谓，看活动内容"],
      zhHant: ["一對一深度交流（典型搭子模式）", "三人小團體（平衡熱鬧與深入）", "多人熱鬧局（4人以上，適合桌遊/聚餐）", "無所謂，看活動內容"],
    },
    socialFrequency: {
      en: ["High-touch daily", "Regular 2-3 times/week", "Low but high-quality every 1-2 weeks", "Very low, only when needed"],
      zhHans: ["高强度陪伴（几乎每天都要有互动或见面）", "规律性互动（每周固定2-3次）", "低频但高质量（1-2周一次，但每次玩得尽兴）", "极低频，只在特定需要时联系"],
      zhHant: ["高強度陪伴（幾乎每天都要有互動或見面）", "規律性互動（每週固定2-3次）", "低頻但高質量（1-2週一次，但每次玩得盡興）", "極低頻，只在特定需要時聯繫"],
    },
    socialSpontaneousMeal: {
      en: ["Go immediately", "Probably yes if free", "Hesitate, often decline", "Usually decline"],
      zhHans: ["毫不犹豫，立刻换衣服出门", "看状态，大概率会去", "略微纠结，如果没计划好通常想拒绝", "基本拒绝，无法忍受打破计划"],
      zhHant: ["毫不猶豫，立刻換衣服出門", "看狀態，大概率會去", "略微糾結，如果沒計劃好通常想拒絕", "基本拒絕，無法忍受打破計劃"],
    },
    socialActivityRole: {
      en: ["Lead planner", "Active advisor", "Easy follower", "Joint decision on everything"],
      zhHans: ["主导规划者（查路线、订座、拍板决定）", "积极参谋（提供建议，但最终听对方的）", "佛系跟随者（只要能定下来，完全交给你）", "纯AA制共同决策（每一步都商量着来）"],
      zhHant: ["主導規劃者（查路線、訂座、拍板決定）", "積極參謀（提供建議，但最終聽對方的）", "佛系跟隨者（只要能定下來，完全交給你）", "純AA制共同決策（每一步都商量著來）"],
    },
    socialFoodConflict: {
      en: ["Argue for my pick", "Find a third option", "Compromise to their pick", "Take turns"],
      zhHans: ["据理力争，试图让对方接受A店更好", "寻找两家店的共同点或第三选择", "直接妥协，去吃B店", "这次听我的，下次听你的，轮着来"],
      zhHant: ["據理力爭，試圖讓對方接受A店更好", "尋找兩家店的共同點或第三選擇", "直接妥協，去吃B店", "這次聽我的，下次聽你的，輪著來"],
    },
    socialBudget: {
      en: ["Under 30", "30-100", "100-200", "2000+"],
      zhHans: ["极致性价比（人均30元以下）", "平价舒适（30-100元）", "中档享受（100-200元）", "中高档（2000元+，体验至上）"],
      zhHant: ["極致性價比（人均30元以下）", "平價舒適（30-100元）", "中檔享受（100-200元）", "中高檔（2000元+，體驗至上）"],
    },
    socialDistance: {
      en: ["Walking distance", "Same campus / 10 min bike", "Same city", "Online-first"],
      zhHans: ["步行可达（同宿舍楼/同小区）", "同校区/骑单车10分钟内", "同城市，公共交通方便即可", "线上为主，物理距离无所谓"],
      zhHant: ["步行可達（同宿舍樓/同小區）", "同校區/騎單車10分鐘內", "同城市，公共交通方便即可", "線上為主，物理距離無所謂"],
    },
    socialInterestMatch: {
      en: ["Must match deeply", "Some overlap is enough", "Character over interests", "Only need companionship"],
      zhHans: ["必须深度一致（如都是某爱好骨灰粉，否则聊不来）", "有交集即可，也乐于被安利新领域", "无所谓，人品大于兴趣", "我不需要共同兴趣，只需要陪伴功能"],
      zhHant: ["必須深度一致（如都是某愛好骨灰粉，否則聊不來）", "有交集即可，也樂於被安利新領域", "無所謂，人品大於興趣", "我不需要共同興趣，只需要陪伴功能"],
    },


    romanceIntent: {
      en: ["Long-term partner, seriously considering the future", "Enjoy romance and companionship now, no long-term goal yet", "Start as friends and see where it goes", "Still exploring / not sure yet"],
      zhHans: ["寻找长期稳定的伴侣，认真考虑未来", "享受当下的浪漫与陪伴，暂不设长远目标", "先从朋友做起，顺其自然看感觉", "还不明确，探索中"],
      zhHant: ["尋找長期穩定的伴侶，認真考慮未來", "享受當下的浪漫與陪伴，暫不設長遠目標", "先從朋友做起，順其自然看感覺", "還不明確，探索中"],
    },
    romancePace: {
      en: ["Fast burn — high frequency, define the relationship quickly", "Slow burn — need time to observe and understand", "No preset pace — follow the vibe"],
      zhHans: ["快速升温，高频互动，迅速确立关系", "慢热型，需要较长时间观察与了解", "没有预设节奏，跟随相处状态自然流动"],
      zhHant: ["快速升溫，高頻互動，迅速確立關係", "慢熱型，需要較長時間觀察與了解", "沒有預設節奏，跟隨相處狀態自然流動"],
    },
    romancePartnerTraits: {
      en: ["Looks and physical attraction", "Intelligence and education", "Emotional stability and maturity", "Humor and zest for life", "Ambition and career prospects", "Loyalty and reliability", "Gentleness and care", "Shared interests and values"],
      zhHans: ["外貌与性吸引力", "智力与学历", "情绪稳定性与成熟度", "幽默感与生活情趣", "上进心与事业前景", "忠诚与可靠度", "温柔体贴与照顾力", "相近的兴趣与价值观"],
      zhHant: ["外貌與性吸引力", "智力與學歷", "情緒穩定性與成熟度", "幽默感與生活情趣", "上進心與事業前景", "忠誠與可靠度", "溫柔體貼與照顧力", "相近的興趣與價值觀"],
    },
    romanceContactDensity: {
      en: ["High-touch — share everything, eat most meals together", "Regular rhythm — daily chat and goodnight calls", "Independent but intertwined — quiet when busy, quality time when free", "Spiritual resonance — not always glued, but always felt"],
      zhHans: ["高黏度：随时随地分享，恨不得每顿饭都一起吃", "规律依赖：每天有固定聊天和晚安电话即可", "独立又交织：忙时互不打扰，但一有空就高质量陪伴", "精神共鸣型：不一定要时刻腻着，但心里知道对方在"],
      zhHant: ["高黏度：隨時隨地分享，恨不得每頓飯都一起吃", "規律依賴：每天有固定聊天和晚安電話即可", "獨立又交織：忙時互不打擾，但一有空就高質量陪伴", "精神共鳴型：不一定要時刻膩著，但心裡知道對方在"],
    },
    romancePersonalSpace: {
      en: ["Need a lot of space — too much closeness feels suffocating", "Moderate distance — keep my own circle and alone time", "Prefer merging — blurred boundaries feel safer", "Fully depends on the other person — I can adapt"],
      zhHans: ["需要较大空间，有时会因对方太黏而感到压迫", "适度的距离，保留独立社交圈和独处时间", "偏爱融合，界限越模糊越有安全感", "完全取决于对方，我都能调整"],
      zhHant: ["需要較大空間，有時會因對方太黏而感到壓迫", "適度的距離，保留獨立社交圈和獨處時間", "偏愛融合，界限越模糊越有安全感", "完全取決於對方，我都能調整"],
    },
    romanceConflictStyle: {
      en: ["Debate head-on until resolved", "Pause and cool down, then talk deeply", "Compromise first to keep harmony", "Avoid — silence or change the topic"],
      zhHans: ["立刻正面辩论，不解决问题不罢休", "先暂停冷静，等彼此情绪平复后再深谈", "倾向于先妥协退让，以维持和谐", "回避冲突，用沉默或转移话题来冷处理"],
      zhHant: ["立刻正面辯論，不解決問題不罷休", "先暫停冷靜，等彼此情緒平復後再深談", "傾向於先妥協退讓，以維持和諧", "回避衝突，用沉默或轉移話題來冷處理"],
    },
    romanceOppositeSexBoundary: {
      en: ["Avoid suspicion — limit one-on-one contact", "Normal social life is fine — just be transparent", "Full trust — no interference", "Depends on the person and situation"],
      zhHans: ["应尽量避嫌，减少单独接触，给人安全感", "可以有正常社交，但需坦诚告知，不隐瞒", "完全信任对方，不做任何干涉", "说不清，因人因事而异"],
      zhHant: ["應盡量避嫌，減少單獨接觸，給人安全感", "可以有正常社交，但需坦誠告知，不隱瞞", "完全信任對方，不做任何干涉", "說不清，因人因事而異"],
    },
    romanceMoneyView: {
      en: ["Must align closely — different habits cause friction", "Same big picture is enough — details can adapt", "Financial independence — no interference", "Doesn't matter as long as love is strong"],
      zhHans: ["必须高度一致，消费习惯不同容易产生矛盾", "大方向一致即可（如储蓄观、享乐观），细节可磨合", "双方财务独立，互不干涉", "无所谓，只要感情好"],
      zhHant: ["必須高度一致，消費習慣不同容易產生矛盾", "大方向一致即可（如儲蓄觀、享樂觀），細節可磨合", "雙方財務獨立，互不干預", "無所謂，只要感情好"],
    },
    romanceGiveTake: {
      en: ["Happy to give more — their joy matters most", "Seek rough balance — equity sustains love", "Hope they initiate and give more", "Haven't thought much — depends"],
      zhHans: ["我乐意多付出，对方开心就好", "追求大致对等，平衡才能长久", "我更希望对方多主动、多付出", "没有仔细想过，视情况而定"],
      zhHant: ["我樂意多付出，對方開心就好", "追求大致對等，平衡才能長久", "我更希望對方多主動、多付出", "沒有仔細想過，視情況而定"],
    },
    romanceFoundation: {
      en: ["Passion — attraction and fresh spark", "Intimacy — aligned values, talk like best friends", "Commitment — shared future plans and compromise", "Growth — be your truest self and lift each other"],
      zhHans: ["互相的吸引和不断刷新的新鲜感和心动感（激情主导）", "三观一致，能像好朋友一样深度交流（亲密主导）", "对未来的规划一致，愿意为共同目标妥协（承诺主导）", "互相成就，能在对方面前做最真实的自己（成长导向）"],
      zhHant: ["互相的吸引和不斷刷新的新鮮感和心動感（激情主導）", "三觀一致，能像好朋友一樣深度交流（親密主導）", "對未來的規劃一致，願意為共同目標妥協（承諾主導）", "互相成就，能在對方面前做最真實的自己（成長導向）"],
    },
    romanceMatchStyle: {
      en: ["Mirror me — highly similar", "Complement me — fill my gaps", "Expand my world — show me new things", "Someone I can influence and lead"],
      zhHans: ["世界上的另一个我（高度相似的镜像）", "互补的另一半（性格或能力上弥补我的不足）", "一个可以带我探索新世界的人", "一个可以被我所影响和引领的人"],
      zhHant: ["世界上的另一個我（高度相似的鏡像）", "互補的另一半（性格或能力上彌補我的不足）", "一個可以帶我探索新世界的人", "一個可以被我影響和引領的人"],
    },

    studyMode: {
      en: ["Online", "Offline"],
      zhHans: ["线上", "线下"],
      zhHant: ["線上", "線下"],
    },
    studyOnlineMethods: {
      en: ["WeChat/QQ and similar apps", "Video meetings", "Other (please specify)"],
      zhHans: ["微信/QQ等社交软件", "视频会议", "其他，请输入"],
      zhHant: ["微信/QQ等社交軟件", "視頻會議", "其他，請輸入"],
    },
    studyOfflineMethods: {
      en: ["On-campus meetup", "Library", "Other (please specify)"],
      zhHans: ["学校面对面碰头", "图书馆", "其他，请输入"],
      zhHant: ["學校面對面碰頭", "圖書館", "其他，請輸入"],
    },
    studyPeakTime: {
      en: ["Morning lark (06:00-09:00 peak)", "Late morning (09:00-12:00)", "Afternoon (14:00-18:00)", "Night owl (20:00-24:00+)", "Variable (depends on the day)"],
      zhHans: ["晨型人（06:00-09:00 效率巅峰）", "上午型（09:00-12:00）", "下午型（14:00-18:00）", "夜猫子型（20:00-24:00 甚至更晚）", "波动型（没有固定规律，视状态而定）"],
      zhHant: ["晨型人（06:00-09:00 效率巔峰）", "上午型（09:00-12:00）", "下午型（14:00-18:00）", "夜貓子型（20:00-24:00 甚至更晚）", "波動型（沒有固定規律，視狀態而定）"],
    },
    studySessionLength: {
      en: ["Sprint (25-30 min, Pomodoro)", "Medium (45-60 min)", "Endurance (1.5-3 hours)", "Burst (highly variable)"],
      zhHans: ["短跑型（25-30分钟，必须休息，番茄钟拥护者）", "中程型（45-60分钟，课表化节奏）", "耐力型（1.5-3小时，进入心流后不愿被打断）", "爆发型（看任务紧迫度，时长极度不稳定）"],
      zhHant: ["短跑型（25-30分鐘，必須休息，番茄鐘擁護者）", "中程型（45-60分鐘，課表化節奏）", "耐力型（1.5-3小時，進入心流後不願被打斷）", "爆發型（看任務緊迫度，時長極度不穩定）"],
    },
    studySyncFreq: {
      en: ["High-touch daily check-ins", "Regular 3-5 deep sessions/week", "Low-frequency 1-2/week", "Async companionship"],
      zhHans: ["高频陪伴（每天都要互相打卡或简短交流）", "规律互动（每周固定3-5次深度讨论）", "低频辅助（每周1-2次，主要用于答疑和进度对齐）", "异步存在（不需要同步，看到消息回复即可，侧重心理陪伴）"],
      zhHant: ["高頻陪伴（每天都要互相打卡或簡短交流）", "規律互動（每週固定3-5次深度討論）", "低頻輔助（每週1-2次，主要用於答疑和進度對齊）", "異步存在（不需要同步，看到消息回覆即可，側重心理陪伴）"],
    },
    studyLearningChannel: {
      en: ["Visual", "Auditory", "Kinesthetic / hands-on", "Mixed"],
      zhHans: ["视觉型（必须看图表、PPT、教材文字才能理解）", "听觉型（听课效率最高，喜欢听播客或与他人讨论）", "动觉/触觉型（必须动手做笔记、画图、做实验才能记住）", "混合型（无明显偏好）"],
      zhHant: ["視覺型（必須看圖表、PPT、教材文字才能理解）", "聽覺型（聽課效率最高，喜歡聽播客或與他人討論）", "動覺/觸覺型（必須動手做筆記、畫圖、做實驗才能記住）", "混合型（無明顯偏好）"],
    },
    studyEnvironment: {
      en: ["Absolute silence", "White noise / cafe vibe", "Light social study room", "Anywhere works"],
      zhHans: ["绝对静默（需要像图书馆死角一样的绝对安静）", "白噪音背景（咖啡馆、雨声、空调声更让你专注）", "轻度社交环境（有人但互不打扰的自习室，看到别人努力更安心）", "完全不受限（地铁、家里、床上都能学）"],
      zhHant: ["絕對靜默（需要像圖書館死角一樣的絕對安靜）", "白噪音背景（咖啡館、雨聲、空調聲更讓你專注）", "輕度社交環境（有人但互不打擾的自習室，看到別人努力更安心）", "完全不受限（地鐵、家裡、床上都能學）"],
    },
    studyGoalType: {
      en: ["GPA focused", "Exam sprint", "Skill building", "Startup / competition", "Interest exploration", "Other"],
      zhHans: ["绩点为王（保研/刷高GPA/评奖学金）", "备考冲刺（考研/考公/考编/出国标化考试）", "能力补完（学软件、练口语、做项目，为求职准备）", "创业或竞赛（寻找同学组建团队共同创业/打比赛）", "兴趣探索（辅修/课外阅读，暂时没有功利性压力）", "其他"],
      zhHant: ["績點為王（保研/刷高GPA/評獎學金）", "備考衝刺（考研/考公/考編/出國標化考試）", "能力補完（學軟件、練口語、做項目，為求職準備）", "創業或競賽（尋找同學組建團隊共同創業/打比賽）", "興趣探索（輔修/課外閱讀，暫時沒有功利性壓力）", "其他"],
    },
    studyMotivation: {
      en: ["Intrinsic curiosity", "External rewards / pressure", "Competition", "Anxiety avoidance"],
      zhHans: ["内在求知（弄懂难题的快感，对知识的纯粹好奇）", "外部奖惩（高绩点、证书、父母期望、怕挂科）", "竞争与超越（要比身边的人做得更好）", "焦虑规避（如果不学习就感到恐慌、落后于时代）"],
      zhHant: ["內在求知（弄懂難題的快感，對知識的純粹好奇）", "外部獎懲（高績點、證書、父母期望、怕掛科）", "競爭與超越（要比身邊的人做得更好）", "焦慮規避（如果不學習就感到恐慌、落後於時代）"],
    },
    studyPartnerRole: {
      en: ["Strict accountability partner", "Emotional cheerleader", "Knowledge explainer", "Quiet co-presence", "Resource ally"],
      zhHans: ["严格的监督者（无情打卡机器）", "提供情绪价值的鼓励者", "传道授业的解惑者（能解答你的知识盲区）", "安静的陪同者（仅仅是在旁边一起坐着各学各的）", "资源分享的同盟（交换笔记、历年考题）"],
      zhHant: ["嚴格的監督者（無情打卡機器）", "提供情緒價值的鼓勵者", "傳道授業的解惑者（能解答你的知識盲區）", "安靜的陪同者（僅僅是在旁邊一起坐著各學各的）", "資源分享的同盟（交換筆記、歷年考題）"],
    },
    studyHelpStyle: {
      en: ["Give the full answer", "Socratic step-by-step guidance", "Share links / materials", "Stay quiet until asked"],
      zhHans: ["直接给出完整答案和最优解", "一步步口头引导，像苏格拉底式追问", "扔给他一个相关的资料链接或网课，让他自己悟", "安静陪着，直到他主动问你"],
      zhHant: ["直接給出完整答案和最優解", "一步步口頭引導，像蘇格拉底式追問", "扔給他一個相關的資料連結或網課，讓他自己悟", "安靜陪著，直到他主動問你"],
    },
    studyFreeRider: {
      en: ["Quietly do their share too", "Private reminder", "Call it out in the group", "Report or remove them"],
      zhHans: ["忍气吞声，默默把他的那份也做了", "私下沟通，给对方一个体面的提醒", "在群里直接公开指出，要求明确分工", "绝不容忍，直接向老师报告或将其除名"],
      zhHant: ["忍氣吞聲，默默把他的那份也做了", "私下溝通，給對方一個體面的提醒", "在群裡直接公開指出，要求明確分工", "絕不容忍，直接向老師報告或將其除名"],
    },
    studySelfControl: {
      en: ["1", "2", "3", "4", "5"],
      zhHans: ["1", "2", "3", "4", "5"],
      zhHant: ["1", "2", "3", "4", "5"],
    },
    studyPlanDisruption: {
      en: ["Very frustrated", "Slightly annoyed but replan quickly", "Unbothered", "Secretly relieved"],
      zhHans: ["极度烦躁，甚至影响后续学习效率", "略显不快，但能快速重新规划时间", "完全无感，随遇而安", "甚至有点开心（终于有理由不用学习了）"],
      zhHant: ["極度煩躁，甚至影響後續學習效率", "略顯不快，但能快速重新規劃時間", "完全無感，隨遇而安", "甚至有點開心（終於有理由不用學習了）"],
    },
    studyMajorMatch: {
      en: ["Same major", "Related / interdisciplinary", "Completely different", "Major doesn't matter"],
      zhHans: ["同一专业（深度研讨，攻克硬核难题）", "相近交叉（如数学+计算机，经济学+社会学）", "完全无关（为了在休息时能聊点完全不同的东西，换脑子）", "无所谓专业，只要学习习惯合拍"],
      zhHant: ["同一專業（深度研討，攻克硬核難題）", "相近交叉（如數學+計算機，經濟學+社會學）", "完全無關（為了在休息時能聊點完全不同的東西，換腦子）", "無所謂專業，只要學習習慣合拍"],
    },
    goal: {
      en: ["Study partner", "Social companion", "Romance partner"],
      zhHans: ["学习伙伴", "社交搭子", "恋爱对象"],
      zhHant: ["學習夥伴", "社交搭子", "戀愛對象"],
    },
    chatStyle: {
      en: ["Light and casual", "Deep and thoughtful", "Playful and witty", "Warm and gentle", "Direct and efficient"],
      zhHans: ["轻松简短", "深度长聊", "幽默玩梗", "温暖细腻", "直接高效"],
      zhHant: ["輕鬆簡短", "深度長聊", "幽默玩梗", "溫暖細膩", "直接高效"],
    },
    taboo: {
      en: ["Family / parents", "Relationship history", "Grades / GPA", "Money / salary", "Politics", "Religion", "No strong taboos"],
      zhHans: ["家庭/父母", "感情史", "成绩/GPA", "薪资/钱", "政治", "宗教", "没有特别忌讳"],
      zhHant: ["家庭/父母", "感情史", "成績/GPA", "薪資/錢", "政治", "宗教", "沒有特別忌諱"],
    },
  },
};
