window.DARLINK_QUESTIONNAIRE = {
  version: "lyssa-2026-06-29",
  registration: [
    { id: "nickname", label: "你的昵称？", type: "text", required: true },
    { id: "school", label: "你来自哪所高校？", type: "text", required: true },
    { id: "email", label: "请输入有效的学校邮箱？", type: "text", required: true },
    { id: "gender", label: "你的性别是？", type: "choice", required: true, options: ["男", "女"] },
    { id: "majorDirection", label: "你的专业方向是？", type: "text", required: true },
    { id: "photoConsent", label: "你愿意提供照片，或符合你气质/样貌的照片吗？", type: "choice", required: false, options: ["愿意", "暂不提供"] },
    { id: "contact", label: "为了让其他同学能够联系到你，你愿意留下你的联系方式吗？", type: "choice", required: false, options: ["电话号码", "微信", "WhatsApp", "QQ", "Instagram", "Facebook", "其他", "不愿意，仅本平台聊天"] },
  ],
  diversion: [
    { id: "goal", label: "如你所知，Darlink 可以帮助你匹配到有相同目的的朋友，现阶段你想找？", type: "choice", required: true, options: ["学习伙伴", "社交搭子", "恋爱对象"] },
    { id: "studyExpectation", label: "如果是学习伙伴：你期待和对方在什么方面合作？", type: "text", required: false },
    { id: "socialActivities", label: "如果是社交搭子：你想和对方进行什么娱乐活动？", type: "text", required: false },
    { id: "romanceGender", label: "如果是恋爱对象：你想找的对象的性别？", type: "choice", required: false, options: ["男", "女"] },
    { id: "heightWeight", label: "如果是恋爱对象：你愿意透露你的身高和体重吗？", type: "text", required: false },
  ],
  initialPersona: [
    { id: "age", label: "你愿意透露你的年龄吗？如不愿意，可以填写保密。", type: "text", required: true },
    { id: "tabooTopics", label: "哪些话题让你觉得不舒服？", type: "multi", required: true, options: ["家庭/父母", "感情史", "成绩/GPA", "薪资/钱", "政治", "宗教", "没有特别忌讳"] },
    { id: "selfDescriptor", label: "如果用一个词来形容你，什么词最贴切？", type: "text", required: true },
    { id: "catchphrase", label: "你有什么口头禅吗？", type: "text", required: true },
    { id: "mbti", label: "你了解 MBTI 吗，你是什么类型的人格？", type: "text", required: true },
  ],
  modeQuestionnaires: {
    study: {
      title: "学习搭子专项问卷",
      partA: [
        { id: "study_core_01", label: "你想要以什么方式进行学习交流？", type: "choice", required: true, options: ["线上", "线下"] },
        { id: "study_online_methods", label: "你想采取什么方式进行线上交流？", type: "multi", required: true, options: ["微信/QQ 等社交软件", "视频会议", "其他，请输入"] },
        { id: "study_offline_methods", label: "你想采取什么方式进行线下交流？", type: "multi", required: true, options: ["学校面对面碰头", "图书馆", "其他，请输入"] },
        { id: "study_core_02", label: "你的高效学习时段偏好是？", type: "choice", required: true, options: ["晨型人（06:00-09:00）", "上午型（09:00-12:00）", "下午型（14:00-18:00）", "夜猫子型（20:00-24:00 甚至更晚）", "波动型"] },
        { id: "study_core_03", label: "你理想的单次连续学习时长是？", type: "choice", required: true, options: ["短跑型", "中程型", "耐力型", "爆发型"] },
        { id: "study_core_04", label: "你每周能接受的与学习伙伴同步互动频率是？", type: "choice", required: true, options: ["高频陪伴", "规律互动", "低频辅助", "异步存在"] },
        { id: "study_core_05", label: "输入新知识时，你依赖的“第一感官通道”是？", type: "choice", required: true, options: ["视觉型", "听觉型", "动觉/触觉型", "混合型"] },
        { id: "study_core_06", label: "你习惯的学习环境氛围是？", type: "choice", required: true, options: ["绝对静默", "白噪音背景", "轻度社交环境", "完全不受限"] },
        { id: "study_core_07", label: "你进行匹配的目标属于哪一类？", type: "choice", required: true, options: ["绩点为王", "备考冲刺", "能力补完", "创业或竞赛", "兴趣探索", "其他"] },
        { id: "study_core_08", label: "驱动你学习的核心燃料是什么？", type: "choice", required: true, options: ["内在求知", "外部奖惩", "竞争与超越", "焦虑规避"] },
        { id: "study_core_09", label: "你希望你的学习伙伴在关系中扮演什么角色？", type: "multi", required: true, options: ["严格的监督者", "提供情绪价值的鼓励者", "传道授业的解惑者", "安静的陪同者", "资源分享的同盟"] },
        { id: "study_core_10", label: "当小组作业中出现“搭便车”的成员，你的直觉反应是？", type: "choice", required: true, options: ["忍气吞声", "私下沟通", "群里公开指出", "向老师报告或除名"] },
        { id: "study_core_11", label: "学习伙伴在做一道你非常擅长的题时突然卡壳了，你倾向于？", type: "choice", required: true, options: ["直接给答案", "一步步口头引导", "给资料让他自己悟", "安静陪着直到他问"] },
        { id: "study_core_12", label: "请评价你的“学习自控力”。", type: "rating", required: true, min: 1, max: 5 },
        { id: "study_core_13", label: "当你学习计划被突发琐事打乱时，你的情绪反应是？", type: "choice", required: true, options: ["极度烦躁", "略显不快但能重规划", "随遇而安", "甚至有点开心"] },
        { id: "study_core_14", label: "你目前的专业大类归属？", type: "choice", required: true, options: ["理工类", "经管社科类", "人文艺术类", "医学与生命科学"] },
        { id: "study_core_15", label: "你希望伙伴的专业与你是什么关系？", type: "choice", required: true, options: ["同一专业", "相近交叉", "完全无关", "无所谓专业"] },
      ],
      partB: [
        { id: "study_custom_intro", label: "假如别人看到你的数字人，和你志同道合，你最想让“你”和别人说什么？", type: "text", required: true },
      ],
    },
    friend: {
      title: "社交搭子专项问卷",
      partA: [
        { id: "friend_core_01", label: "你最想通过本平台寻找的“搭子”类型是？", type: "choice", required: true, options: ["纯聊天 / 情绪树洞", "饭搭子", "旅游搭子", "兴趣搭子", "万能搭子"] },
        { id: "friend_core_02", label: "你参与社交活动的核心动力是什么？", type: "choice", required: true, options: ["缓解孤独", "获得快乐与新鲜体验", "寻找同频共鸣", "纯粹功利性互助"] },
        { id: "friend_core_03", label: "你理想的社交规模通常是？", type: "choice", required: true, options: ["一对一深度交流", "三人小团体", "多人热闹局", "无所谓"] },
        { id: "friend_core_04", label: "社交活动结束后，你的能量状态通常是？", type: "choice", required: true, options: ["精疲力尽", "轻微疲惫", "更兴奋", "毫无波动"] },
        { id: "friend_core_05", label: "你周末最自然的“默认状态”是？", type: "choice", required: true, options: ["宅着刷手机/看剧/打游戏", "独自咖啡厅/图书馆/散步", "主动约人组局", "固定社团或运动", "临时起意"] },
        { id: "friend_core_06", label: "你与搭子理想的互动频率是？", type: "choice", required: true, options: ["高强度陪伴", "规律性互动", "低频但高质量", "极低频"] },
        { id: "friend_core_07", label: "如果搭子在饭点前一小时突然问“出来吃饭吗”，你的反应是？", type: "choice", required: true, options: ["立刻出门", "看状态，大概率会去", "略微纠结", "基本拒绝"] },
        { id: "friend_core_08", label: "在一次共同活动中，你习惯扮演的角色是？", type: "choice", required: true, options: ["主导规划者", "积极参谋", "佛系跟随者", "纯 AA 制共同决策"] },
        { id: "friend_core_09", label: "当你想吃 A 店但搭子想吃 B 店时，你的本能反应是？", type: "choice", required: true, options: ["据理力争", "找第三选择", "直接妥协", "轮着来"] },
        { id: "friend_core_10", label: "你日常可接受的一次搭子活动（吃饭/下午茶/门票等）人均消费是？", type: "multi", required: true, options: ["30 元以下", "30-100 元", "100-200 元", "2000 元+"] },
        { id: "friend_core_11", label: "和刚认识一周的搭子聊天时，你更倾向于？", type: "choice", required: true, options: ["快速交换兴趣爱好", "以活动本身为话题", "安静倾听", "随性"] },
        { id: "friend_core_12", label: "你对于朋友向你倾诉负能量的感觉是？", type: "choice", required: true, options: ["乐意倾听", "可以听但希望适可而止", "略微不适", "被侵犯边界"] },
        { id: "friend_core_13", label: "旅游或外出时，如果搭子做了你不认同的小事，你最可能会？", type: "choice", required: true, options: ["当面温和指出", "事后委婉表达", "心里扣分", "无所谓"] },
        { id: "friend_core_14", label: "你能接受与搭子的最大空间距离是？", type: "choice", required: true, options: ["步行可达", "同校区/骑车 10 分钟内", "同城市", "线上为主"] },
        { id: "friend_core_15", label: "对于共同兴趣的匹配程度，你的要求是？", type: "choice", required: true, options: ["必须深度一致", "有交集即可", "人品大于兴趣", "只需要陪伴功能"] },
      ],
      partB: [
        { id: "friend_custom_joke", label: "假如别人看到你的数字人，你想和 ta 分享什么笑话？", type: "text", required: true },
      ],
    },
    romance: {
      title: "恋爱对象专项问卷",
      partA: [
        { id: "romance_core_01", label: "你目前寻找恋爱对象的主要意图是？", type: "choice", required: true, options: ["长期稳定伴侣", "享受当下浪漫与陪伴", "先从朋友做起", "还不明确"] },
        { id: "romance_core_02", label: "你更适应哪种恋爱推进节奏？", type: "choice", required: true, options: ["快速升温", "慢热型", "自然流动"] },
        { id: "romance_core_03", label: "在以下特质中，选出你在伴侣身上最看重的三项。", type: "multi", required: true, max: 3, options: ["外貌与性吸引力", "智力与学历", "情绪稳定性与成熟度", "幽默感与生活情趣", "上进心与事业前景", "忠诚与可靠度", "温柔体贴与照顾力", "相近的兴趣与价值观"] },
        { id: "romance_core_04", label: "你理想中与伴侣的日常联络密度是？", type: "choice", required: true, options: ["高黏度", "规律依赖", "独立又交织", "精神共鸣型"] },
        { id: "romance_core_05", label: "在亲密关系中，你需要多少“个人空间”？", type: "choice", required: true, options: ["较大空间", "适度距离", "偏爱融合", "取决于对方"] },
        { id: "romance_core_06", label: "当你与伴侣发生激烈争执时，你的本能反应更接近于？", type: "choice", required: true, options: ["正面辩论", "暂停冷静后深谈", "妥协退让", "回避冲突"] },
        { id: "romance_core_07", label: "关于伴侣的异性交往边界，你更接近哪种态度？", type: "choice", required: true, options: ["尽量避嫌", "正常社交但坦诚告知", "完全信任不干涉", "因人因事而异"] },
        { id: "romance_core_08", label: "消费与金钱观方面，你更愿意接受与伴侣之间存在多大差异？", type: "choice", required: true, options: ["必须高度一致", "大方向一致即可", "财务独立", "无所谓"] },
        { id: "romance_core_09", label: "在付出与回报的感知上，你内心更接近哪种模式？", type: "choice", required: true, options: ["我乐意多付出", "追求大致对等", "希望对方多付出", "视情况而定"] },
        { id: "romance_core_10", label: "你认为一段长久健康的恋爱关系，最不可或缺的基石是？", type: "choice", required: true, options: ["吸引和新鲜感", "三观一致深度交流", "未来规划一致", "互相成就"] },
        { id: "romance_core_11", label: "你更希望算法为你匹配怎样的潜在对象？", type: "choice", required: true, options: ["世界上的另一个我", "互补的另一半", "带我探索新世界的人", "被我影响和引领的人"] },
      ],
      partB: [
        { id: "romance_custom_attractive_point", label: "你认为你最能打动 ta 的是哪一点？", type: "text", required: true },
        { id: "romance_custom_moves_them", label: "你认为你最有可能被 ta 的哪一点打动？", type: "text", required: true },
      ],
    },
  },
};
