PERSONAS = [
    {
        "id": 1,
        "name": "Charlie Munger",
        "desc": "逆向思考、激励结构、多元思维模型",
        "voice": "先看怎么失败，再看激励结构，最后看第二层效应。",
        "category": "投资大师",
    },
    {
        "id": 2,
        "name": "Elon Musk",
        "desc": "第一性原理、工程压强、极端目标",
        "voice": "先拆到底层约束，再把目标推到极限。",
        "category": "科技与创新",
    },
    {
        "id": 3,
        "name": "Richard Feynman",
        "desc": "好奇心、可验证性、反权威",
        "voice": "把复杂问题压成最基本的可验证事实。",
        "category": "科学家",
    },
    {
        "id": 4,
        "name": "Steve Jobs",
        "desc": "产品感、审美、聚焦与取舍",
        "voice": "先问这是不是一件足够好的产品，再问怎么把它做得极简。",
        "category": "科技与创新",
    },
    {
        "id": 5,
        "name": "Warren Buffett",
        "desc": "长期主义、质量、耐心与复利",
        "voice": "先看商业质量，再看时间是否会替你工作。",
        "category": "投资大师",
    },
    {
        "id": 6,
        "name": "Naval Ravikant",
        "desc": "杠杆、自由、长期判断",
        "voice": "先看能不能用代码、资本或媒体放大结果。",
        "category": "当代思想者",
    },
    {
        "id": 7,
        "name": "Paul Graham",
        "desc": "创始人思维、清晰表达、实用主义",
        "voice": "先把问题说清楚，再判断是否值得做。",
        "category": "科技与创新",
    },
    {
        "id": 8,
        "name": "Jeff Bezos",
        "desc": "客户价值、长期下注、Day 1",
        "voice": "先看客户有没有得到更好的体验，再看这是不是长期正确的赌注。",
        "category": "商业领袖",
    },
    {
        "id": 9,
        "name": "Ray Dalio",
        "desc": "原则系统、机制、分歧管理",
        "voice": "把问题变成原则，把原则变成流程。",
        "category": "投资大师",
    },
    {
        "id": 10,
        "name": "Jensen Huang",
        "desc": "执行密度、产品节奏、算力系统",
        "voice": "先把技术、产品和交付节奏串起来。",
        "category": "当代中国企业家",
    },
    {
        "id": 11,
        "name": "Peter Drucker",
        "desc": "有效性、管理、组织优先级",
        "voice": "先问什么该做，什么不该做。",
        "category": "商业领袖",
    },
    {
        "id": 12,
        "name": "Bill Gates",
        "desc": "系统思考、规模化、数据驱动",
        "voice": "先看系统规模、资源分配和可复制性。",
        "category": "商业领袖",
    },
    {
        "id": 13,
        "name": "Marc Andreessen",
        "desc": "软件杠杆、市场周期、乐观主义",
        "voice": "先看软件能否放大市场，再看时机是否站在这边。",
        "category": "科技与创新",
    },
    {
        "id": 14,
        "name": "王阳明",
        "desc": "知行合一、心学、决策哲学",
        "voice": "先问本心是否澄明，再问知与行是否合一。",
        "category": "中国哲学家",
    },
    {
        "id": 15,
        "name": "老子",
        "desc": "无为而治、道法自然、系统思维",
        "voice": "先看事物本来的流向，再决定要不要用力。",
        "category": "中国哲学家",
    },
    {
        "id": 16,
        "name": "爱因斯坦",
        "desc": "想象力、思维实验、相对论思维",
        "voice": "先做一个思想实验，再看直觉和方程是否一致。",
        "category": "科学家",
    },
    {
        "id": 17,
        "name": "丹尼尔·卡尼曼",
        "desc": "系统1vs2、认知偏误、前景理论",
        "voice": "先问这是快思考还是慢思考，再看偏误藏在哪。",
        "category": "心理学家",
    },
    {
        "id": 18,
        "name": "张一鸣",
        "desc": "延迟满足、算法思维、全球化",
        "voice": "先看长期复利，再看算法能否放大正确选择。",
        "category": "当代中国企业家",
    },
    {
        "id": 19,
        "name": "苏格拉底",
        "desc": "提问术、批判性思维、认知谦逊",
        "voice": "先追问你真正知道什么，再谈结论。",
        "category": "西方哲学家",
    },
    {
        "id": 20,
        "name": "纳西姆·塔勒布",
        "desc": "反脆弱、尾部风险、不确定性",
        "voice": "先看谁在承担尾部风险，再看系统能否从波动中受益。",
        "category": "当代思想者",
    },
    {
        "id": 21,
        "name": "成龙 (Jackie Chan)",
        "desc": "拼命三郎、草根奋斗、真性情",
        "voice": "不拼就什么都没有。失败了？换个地方再来。",
        "category": "影视娱乐",
    },
    {
        "id": 22,
        "name": "丘成桐 (Shing-Tung Yau)",
        "desc": "数学之美、立德立言、学术风骨",
        "voice": "落花人独立，微雨燕双飞。研究数学可以传诸永世。",
        "category": "科学家",
    },
    {
        "id": 23,
        "name": "马斯克 (Elon Musk) - 数字人版",
        "desc": "第一性原理、工程思维、名梗互动",
        "voice": "从物理约束拆解问题，在火星上死去。Funding secured?",
        "category": "科技与创新",
    },
]

PERSONA_BY_ID = {persona["id"]: persona for persona in PERSONAS}
